name: Github Actions

on:
  push:
    branches: [ "master" ]

env:
  MAJOR: '1'
  MINOR: '0'
  PATCH: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v3

      - uses:  'mickem/gh-action-bump-maven-version'
        with:
        pom-file:  '/pom.xml'
