name: Github Actions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Increment version
        uses: 'mickem/gh-action-bump-maven-version@v1.0.0'
        with:
          pom-file: 'pom.xml'

      - name: Save Version
        run: echo "VERSION=$(grep version pom.xml | grep -v -e '<?xml|~'| head -n 1 | sed 's/[[:space:]]//g' | sed -E 's/<.{0,1}version>//g' | awk '{print $1}')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build --build-arg VERSION=$VERSION -t barminz/dependabot:${{ env.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push current version
        run: docker push barminz/dependabot:${{ env.VERSION }}

      - name: Tag latest
        run: docker tag barminz/dependabot:${{ env.VERSION }} barminz/dependabot:latest

      - name: Push latest
        run: docker push barminz/dependabot:latest
