name: Github Actions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: increment version
        uses: 'mickem/gh-action-bump-maven-version@v1.0.0'
        with:
          pom-file: 'pom.xml'

      - name: Save Version
        run: echo "VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version)" >> $GITHUB_ENV

      - name: Print Version
        run: echo "${{ env.VERSION }}"

      - name: Build the Docker image
        run: docker build -t barminz/dependabot:${{ env.VERSION }} .
