name: Github Actions

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: increment version
        uses: 'mickem/gh-action-bump-maven-version@v1.0.0'
        with:
          pom-file: 'pom.xml'

      - name: Save Version
        run: echo "VERSION=$(grep version pom.xml | grep -v -e '<?xml|~'| head -n 1 | sed 's/[[:space:]]//g' | sed -E 's/<.{0,1}version>//g' | awk '{print $1}')" >> $GITHUB_ENV

      - name: Print Version
        run: echo "${{ env.VERSION }}"

      - name: Build the Docker image
        run: docker build --build-arg VERSION=$VERSION -t barminz/dependabot:${{ env.VERSION }} .
